
export const ACTIVE_PROJECTS_SELECTOR = 'active'
export const INACTIVE_PROJECTS_SELECTOR = 'inactive'
export const ALLOWED_PROJECT_LIST_SELECTORS = [ACTIVE_PROJECTS_SELECTOR, INACTIVE_PROJECTS_SELECTOR]
